[package]
name = "sim"
version = "0.1.0"
edition = "2024"

[dependencies]
z3 = "0.12"
parser = { path = "./parser" }
ir = { path = "./ir" }
encoder = { path = "./encoder" }
enchelper = { path = "./enchelper" }